#!/bin/bash

# Usage: 'VMTranslator.sh source' 
# where 'source' is either a file name in the form Xxx.vm or the name of a folder
# containing one or more .vm files. 'source' may contain a path. If no path is specified,
# the translator operates on the current folder. Output is generated by translating all 
# .vm files specified by 'source' and writing the result in a single 'source'.asm file
# in the dir specified by 'source'.

python3 src/vm_translator.py $1

